import test from 'node:test';
import assert from 'node:assert/strict';
import { CodeSandboxExecutor,createCodeSandboxExecutorFromEnvironment } from '../src/codesandbox-executor.js';
function fakeSdk({failOn=''}={}){const calls=[],sandbox={id:'sandbox-123',connect:async()=>({commands:{run:async(command)=>{calls.push(command);if(failOn&&command.includes(failOn)){const error=new Error('command failed');error.exitCode=2;error.stderr='boom';throw error}return `ok:${command}`}}}),hibernate:async()=>{calls.push('HIBERNATE')}};return{calls,sandbox,sdk:{sandboxes:{create:async()=>sandbox,get:async(id)=>({...sandbox,id})}}}}
test('CodeSandbox executor stages files and runs bounded execution plan',async()=>{const fake=fakeSdk(),executor=new CodeSandboxExecutor({sdk:fake.sdk});const result=await executor.execute({project_id:'demo',files:[{path:'package.json',content:'{"scripts":{"test":"node --test"}}'},{path:'src/index.js',content:'console.log("ok")'}],plan:{steps:[{name:'install',command:['npm','install','--ignore-scripts']},{name:'test',command:['npm','test']}]}});assert.equal(result.passed,true);assert.equal(result.provider,'codesandbox');assert.equal(result.steps.length,2);assert.equal(result.steps[0].status,'success');assert.ok(fake.calls.some(call=>call.includes("'npm' 'install' '--ignore-scripts'")));assert.ok(fake.calls.some(call=>call.includes('base64 -d')));assert.equal(fake.calls.at(-1),'HIBERNATE')});
test('CodeSandbox executor stops after failed command',async()=>{const fake=fakeSdk({failOn:"'npm' 'test'"}),executor=new CodeSandboxExecutor({sdk:fake.sdk});const result=await executor.execute({files:[{path:'package.json',content:'{}'}],plan:{steps:[{name:'test',command:['npm','test']},{name:'build',command:['npm','run','build']}]}});assert.equal(result.passed,false);assert.equal(result.steps.length,1);assert.equal(result.steps[0].exit_code,2);assert.equal(result.steps[0].stderr,'boom');assert.ok(!fake.calls.some(call=>call.includes("'npm' 'run' 'build'")))});
test('CodeSandbox executor rejects traversal paths',async()=>{const fake=fakeSdk(),executor=new CodeSandboxExecutor({sdk:fake.sdk});await assert.rejects(()=>executor.execute({files:[{path:'../secret',content:'x'}],plan:{steps:[]}}),/Unsafe sandbox file path/)});
test('environment factory is disabled without a token',async()=>{assert.equal(await createCodeSandboxExecutorFromEnvironment({}),null)});
test('environment factory supports reusable sandbox id without importing SDK',async()=>{const fake=fakeSdk(),executor=await createCodeSandboxExecutorFromEnvironment({CSB_API_KEY:'token',CODESANDBOX_SANDBOX_ID:'existing-123'},{sdkFactory:async()=>fake.sdk});assert.equal((await executor.health()).sandbox_id,'existing-123');assert.equal((await executor.health()).reusable,true)});
