import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import { dockerArgs,imageIsDigestPinned } from '../src/container-sandbox.js';
import { createSandboxWorker } from '../src/sandbox-worker.js';

test('docker execution applies hardened isolation controls',()=>{const {args}=dockerArgs({workspace:'/tmp/work',command:['npm','test'],network:'off',memoryMb:512,user:'1000:1000'}),joined=args.join(' ');assert.match(joined,/--network none/);assert.match(joined,/--cap-drop=ALL/);assert.match(joined,/no-new-privileges/);assert.match(joined,/--pids-limit 256/);assert.match(joined,/--memory 512m/);assert.match(joined,/--read-only/);assert.match(joined,/--user 1000:1000/);assert.match(joined,/nofile=1024:1024/);assert.match(joined,/HOME=\/tmp/);assert.match(joined,/node:20-alpine npm test/)});

test('registry-only execution requires an isolated registry network',()=>{assert.throws(()=>dockerArgs({workspace:'/tmp/work',command:['npm','install','--ignore-scripts'],network:'registry-only'}),/isolated registry network/);const install=dockerArgs({workspace:'/tmp/work',command:['npm','install','--ignore-scripts'],network:'registry-only',registryNetwork:'sandbox-registry-egress'}).args.join(' ');assert.match(install,/--network sandbox-registry-egress/);assert.doesNotMatch(install,/--network bridge/)});

test('image digest pin detection is strict',()=>{assert.equal(imageIsDigestPinned('node:20-alpine'),false);assert.equal(imageIsDigestPinned(`node@sha256:${'a'.repeat(64)}`),true)});

test('sandbox worker rejects unauthorized execution',async()=>{const server=createSandboxWorker({token:'123456789012345678901234',executor:{execute:async()=>({passed:true,steps:[]})}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const {port}=server.address();const result=await new Promise((resolve,reject)=>{const req=http.request({host:'127.0.0.1',port,path:'/v1/execute',method:'POST',headers:{'content-type':'application/json'}},res=>{let body='';res.on('data',c=>body+=c);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(body)}))});req.on('error',reject);req.end(JSON.stringify({files:[],plan:{steps:[]}}))});await new Promise(resolve=>server.close(resolve));assert.equal(result.status,401);assert.equal(result.body.error,'unauthorized')});

test('sandbox health reports security posture',async()=>{const executor={execute:async()=>({passed:true}),readOnlyRoot:true,user:'1000:1000',registryNetwork:'sandbox-registry-egress',image:`node@sha256:${'a'.repeat(64)}`};const server=createSandboxWorker({token:'123456789012345678901234',executor});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const {port}=server.address();const result=await new Promise((resolve,reject)=>http.get({host:'127.0.0.1',port,path:'/health'},res=>{let body='';res.on('data',c=>body+=c);res.on('end',()=>resolve(JSON.parse(body)))}).on('error',reject));await new Promise(resolve=>server.close(resolve));assert.equal(result.security.read_only_root,true);assert.equal(result.security.non_root_user,true);assert.equal(result.security.registry_network_configured,true);assert.equal(result.security.node_image_digest_pinned,true)});
