import test from 'node:test';
import assert from 'node:assert/strict';
import { DynamicPromptWorkspace } from '../src/dynamic-workspace.js';

function providerFixture(){const calls=[];return{calls,provider:{async research(){calls.push({agentRole:'research'});return{answer:'evidence',sources:[{title:'Source',url:'https://example.gov/rule'}]}},async generate({agentRole,input}){calls.push({agentRole,input});if(agentRole==='dynamic_planner')return{objective:'Plan',approach:'Analyze',specialists:[{name:'Analyst A',focus:'A'},{name:'Analyst B',focus:'B'}]};if(agentRole==='specialist')return{answer:`${input.specialist.name} answer`};if(agentRole==='judge')return{answer:'Judged answer',confidence:88};if(agentRole==='dynamic_qa')return{approved:true,answer:'QA final',quality_score:93,findings:[]};throw new Error('unexpected role')}}}}

test('1 agent uses one model stage and returns direct answer',async()=>{const{calls,provider}=providerFixture();const result=await new DynamicPromptWorkspace({provider}).execute('Simple task',{agentCount:1});assert.equal(result.status,'completed');assert.equal(result.agent_count,1);assert.equal(result.output,'Task Analyst answer');assert.deepEqual(calls.map(x=>x.agentRole),['specialist'])});

test('2 agents defaults to answer plus QA',async()=>{const{calls,provider}=providerFixture();const result=await new DynamicPromptWorkspace({provider}).execute('Normal task',{agentCount:2});assert.equal(result.status,'completed');assert.equal(result.agent_count,2);assert.equal(result.output,'QA final');assert.deepEqual(calls.map(x=>x.agentRole),['specialist','dynamic_qa'])});

test('3 agents adds planner before answer and QA',async()=>{const{calls,provider}=providerFixture();const result=await new DynamicPromptWorkspace({provider}).execute('Planned task',{agentCount:3});assert.equal(result.agent_count,3);assert.deepEqual(calls.map(x=>x.agentRole),['dynamic_planner','specialist','dynamic_qa'])});

test('4 agents uses planner, two specialists and QA without judge',async()=>{const{calls,provider}=providerFixture();const result=await new DynamicPromptWorkspace({provider}).execute('Compare options',{agentCount:4});assert.equal(result.agent_count,4);assert.equal(result.agent_team.length,2);assert.equal(calls.filter(x=>x.agentRole==='specialist').length,2);assert.equal(calls.some(x=>x.agentRole==='judge'),false);assert.equal(calls.at(-1).agentRole,'dynamic_qa')});

test('5 agents runs full planner, two specialists, judge and QA workflow',async()=>{const{calls,provider}=providerFixture();const result=await new DynamicPromptWorkspace({provider}).execute('Hard task',{agentCount:5});assert.equal(result.agent_count,5);assert.equal(result.confidence,88);assert.equal(calls.filter(x=>x.agentRole==='specialist').length,2);assert.equal(calls.some(x=>x.agentRole==='judge'),true);assert.equal(calls.at(-1).agentRole,'dynamic_qa')});

test('research remains optional and can gracefully degrade',async()=>{const calls=[];const provider={async research(){throw new Error('HTTP 429')},async generate({agentRole,input}){calls.push(agentRole);if(agentRole==='specialist')return{answer:'answer without research'};if(agentRole==='dynamic_qa')return{approved:true,answer:'reviewed fallback',quality_score:80};throw new Error('unexpected')}};const result=await new DynamicPromptWorkspace({provider}).execute('Current task',{agentCount:2,research:true});assert.equal(result.status,'completed');assert.equal(result.research_mode,false);assert.equal(result.research_error,'provider_rate_limited');assert.equal(result.output,'reviewed fallback')});

test('follow-up conversation is supplied to the answering agent',async()=>{const calls=[];const provider={async generate({agentRole,input}){calls.push({agentRole,input});if(agentRole==='specialist')return{answer:'shorter revision'};throw new Error('unexpected')}};const conversation=[{role:'user',content:'Write a detailed proposal'},{role:'assistant',content:'Long proposal text'}];const result=await new DynamicPromptWorkspace({provider}).execute('Make it shorter',{agentCount:1,conversation});assert.equal(result.output,'shorter revision');assert.deepEqual(calls[0].input.conversation,conversation);assert.match(calls[0].input.instruction,/follow-up instructions/i)});
