import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import { attachImproveRoutes } from '../src/improve-router.js';

function request(server,{method='GET',path='/',body=null}={}){return new Promise((resolve,reject)=>{const address=server.address();const req=http.request({host:'127.0.0.1',port:address.port,method,path,headers:body?{'content-type':'application/json'}:{}},res=>{const chunks=[];res.on('data',c=>chunks.push(c));res.on('end',()=>resolve({status:res.statusCode,text:Buffer.concat(chunks).toString('utf8')}))});req.on('error',reject);if(body)req.write(JSON.stringify(body));req.end()})}
async function listen(server){await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve)})}

test('Improve page exposes only configured repository choices',async()=>{const server=http.createServer((req,res)=>{res.writeHead(404);res.end()});attachImproveRoutes(server,{allowedRepositories:['sweater9/example'],providerOptions:['auto']});await listen(server);try{const response=await request(server,{path:'/improve'});assert.equal(response.status,200);assert.match(response.text,/sweater9\/example/);assert.match(response.text,/never writes directly to the base branch/i)}finally{server.close()}});

test('Improve API rejects repositories outside the allowlist before invoking workflow',async()=>{let called=false;const improver={async improve(){called=true;return{status:'verified'}}};const server=http.createServer((req,res)=>{res.writeHead(404);res.end()});attachImproveRoutes(server,{improver,allowedRepositories:['sweater9/allowed'],providerOptions:['auto']});await listen(server);try{const response=await request(server,{method:'POST',path:'/api/improve/run',body:{repository:'sweater9/not-allowed',base:'main',request:'change it'}});assert.equal(response.status,403);assert.equal(called,false);assert.equal(JSON.parse(response.text).error,'repository_not_allowed')}finally{server.close()}});

test('Improve API invokes workflow for allowlisted repository',async()=>{let args=null;const improver={async improve(input){args=input;return{repository:input.repository,base:input.base,status:'verified',publication:null,verification:{status:'passed'}}}};const server=http.createServer((req,res)=>{res.writeHead(404);res.end()});attachImproveRoutes(server,{improver,allowedRepositories:['sweater9/allowed'],providerOptions:['auto']});await listen(server);try{const response=await request(server,{method:'POST',path:'/api/improve/run',body:{repository:'sweater9/allowed',base:'main',request:'add a test'}});assert.equal(response.status,200);assert.equal(args.repository,'sweater9/allowed');assert.equal(args.request,'add a test');assert.equal(JSON.parse(response.text).status,'verified')}finally{server.close()}});
