import test from 'node:test';
import assert from 'node:assert/strict';
import { RepositoryImporter } from '../src/repository-importer.js';
import { ExistingRepositoryImprover } from '../src/improve-workflow.js';

test('repository importer bounds and ignores generated/binary files',async()=>{const client={request:async()=>({tree:[{type:'blob',path:'package.json',size:10},{type:'blob',path:'src/app.js',size:10},{type:'blob',path:'node_modules/x.js',size:10},{type:'blob',path:'logo.png',size:10}]}),readFile:async({path})=>({path,sha:`sha-${path}`,content:path==='package.json'?'{"scripts":{"test":"node --test"}}':'export default 1'})};const importer=new RepositoryImporter({client});const result=await importer.import({repository:'o/r',ref:'main'});assert.deepEqual(result.files.map(f=>f.path),['package.json','src/app.js']);assert.equal(result.file_count,2)});

test('improver does not publish when execution cannot be repaired',async()=>{let published=false;const importer={import:async()=>({files:[{path:'package.json',content:'{"scripts":{"test":"node --test"}}',sha:'1'}],manifest:[{path:'package.json'}]})};const provider={generate:async({agentRole})=>agentRole==='repository_analyst'?{plan:'x'}:{files:[{path:'package.json',content:'{"scripts":{"test":"node --test"}}'}]}};const githubClient={createBranch:async()=>{published=true}};const executionRunner={run:async()=>({passed:false,summary:{category:'test'},runtime:'node'})};const improver=new ExistingRepositoryImprover({provider,importer,githubClient,executionRunner,maxRepairAttempts:0});const result=await improver.improve({repository:'o/r',request:'fix it'});assert.equal(result.status,'needs_repair');assert.equal(result.publication,null);assert.equal(published,false)});

test('improver publishes verified changed files to a feature branch and opens PR',async()=>{const calls=[];const importer={import:async()=>({files:[{path:'package.json',content:'{"scripts":{}}',sha:'p1'},{path:'src/a.js',content:'old',sha:'a1'}],manifest:[]})};const provider={generate:async({agentRole})=>agentRole==='repository_analyst'?{plan:'change a'}:{files:[{path:'package.json',content:'{"scripts":{}}'},{path:'src/a.js',content:'new'}]}};const githubClient={createBranch:async x=>calls.push(['branch',x]),updateFile:async x=>calls.push(['update',x.path,x.sha]),createFile:async x=>calls.push(['create',x.path]),compare:async()=>({ahead_by:1}),openPullRequest:async()=>({number:7,url:'x'}),getCiStatus:async()=>({status:'in_progress',checks:[]})};const executionRunner={run:async()=>({passed:true,summary:{steps:[]},runtime:'static'})};const improver=new ExistingRepositoryImprover({provider,importer,githubClient,executionRunner});const result=await improver.improve({repository:'o/r',request:'change a'});assert.equal(result.status,'verified');assert.ok(result.publication.branch.startsWith('improve/'));assert.deepEqual(result.publication.changes,['src/a.js']);assert.ok(calls.some(x=>x[0]==='update'&&x[1]==='src/a.js'&&x[2]==='a1'))});
