import test from 'node:test';
import assert from 'node:assert/strict';
import { createService } from '../src/service.js';
async function withServer(options,fn){const server=createService(options);await new Promise(r=>server.listen(0,'127.0.0.1',r));const{port}=server.address();try{await fn(`http://127.0.0.1:${port}`)}finally{await new Promise(r=>server.close(r))}}
function fixture(){const runs=new Map();const stateStore={async load(id){if(!runs.has(id))throw new Error('Workflow run not found');return runs.get(id)}};const orchestrator={async execute(goal){const run={workflow_run_id:'abc-123',workflow_status:'completed',goal};runs.set(run.workflow_run_id,run);return run},async resume(id){if(!runs.has(id))throw new Error('Workflow run not found');return{...runs.get(id),resumed:true}}};return{orchestrator,stateStore}}

test('root prompt workspace exposes selectable agents and continuation chat',async()=>{const runtime=fixture();await withServer({...runtime,apiKey:'x'.repeat(24)},async base=>{const response=await fetch(base);assert.equal(response.status,200);const body=await response.text();assert.match(body,/Multi-Agent Workspace/);assert.match(body,/Run Workflow/);assert.match(body,/id="agentCount"/);assert.match(body,/1 — Direct answer/);assert.match(body,/5 — Full team \+ Judge \+ QA/);assert.match(body,/id="followupInput"/);assert.match(body,/Continue this conversation/);assert.match(body,/Send follow-up/);assert.match(body,/New conversation/);assert.match(body,/multiAgentHistoryV3/);assert.match(body,/Recent conversations/);assert.match(body,/Service online/)})});

test('public prompt endpoint forwards research, agent count and conversation context',async()=>{const runtime=fixture();let captured=null;const workspace={async execute(goal,options){captured={goal,options};return{workflow_run_id:'w1',status:'completed',goal,output:'Updated result',agents:{},agent_count:options.agentCount,research_mode:Boolean(options.research)}}};await withServer({...runtime,workspace,apiKey:'x'.repeat(24)},async base=>{const conversation=[{role:'user',content:'Original task'},{role:'assistant',content:'Original answer'}];const response=await fetch(`${base}/api/workspace/run`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({goal:'Make it shorter',research:true,agent_count:1,conversation})});assert.equal(response.status,200);const body=await response.json();assert.equal(body.output,'Updated result');assert.equal(body.agent_count,1);assert.deepEqual(captured,{goal:'Make it shorter',options:{research:true,agentCount:1,conversation}})})});

test('agent count defaults to 2 and clamps to 1-5',async()=>{const runtime=fixture();const seen=[];const workspace={async execute(goal,options){seen.push(options.agentCount);return{workflow_run_id:'w',status:'completed',goal,output:'ok',agents:{}}}};await withServer({...runtime,workspace,apiKey:'x'.repeat(24)},async base=>{for(const body of [{goal:'a'},{goal:'b',agent_count:99},{goal:'c',agent_count:-4}])await fetch(`${base}/api/workspace/run`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});assert.deepEqual(seen,[2,5,1])})});

test('conversation input is bounded and normalized',async()=>{const runtime=fixture();let captured;const workspace={async execute(goal,options){captured=options.conversation;return{workflow_run_id:'w',status:'completed',goal,output:'ok',agents:{}}}};await withServer({...runtime,workspace,apiKey:'x'.repeat(24)},async base=>{const conversation=Array.from({length:20},(_,i)=>({role:i%2?'assistant':'bad',content:`m${i}`}));await fetch(`${base}/api/workspace/run`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({goal:'continue',conversation})});assert.equal(captured.length,12);assert.equal(captured[0].content,'m8');assert.equal(captured[0].role,'user');assert.equal(captured[1].role,'assistant')})});

test('health and readiness are public',async()=>{const runtime=fixture();await withServer({...runtime,apiKey:'x'.repeat(24),readinessCheck:async()=>({ok:true,mode:'test'})},async base=>{assert.equal((await fetch(`${base}/health`)).status,200);const ready=await fetch(`${base}/ready`);assert.equal(ready.status,200);assert.equal((await ready.json()).mode,'test')})});
test('workflow APIs require bearer authentication',async()=>{const runtime=fixture();await withServer({...runtime,apiKey:'secret-key-12345678901234'},async base=>{const response=await fetch(`${base}/api/workflows`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({goal:'test'})});assert.equal(response.status,401)})});
test('authenticated workflow can be started and fetched',async()=>{const runtime=fixture(),key='secret-key-12345678901234';await withServer({...runtime,apiKey:key},async base=>{const started=await fetch(`${base}/api/workflows`,{method:'POST',headers:{authorization:`Bearer ${key}`,'content-type':'application/json'},body:JSON.stringify({goal:'Build safely'})});assert.equal(started.status,202);const run=await started.json();const fetched=await fetch(`${base}/api/workflows/${run.workflow_run_id}`,{headers:{authorization:`Bearer ${key}`}});assert.equal(fetched.status,200);assert.equal((await fetched.json()).goal,'Build safely')})});
test('webhook endpoint is isolated from API bearer auth',async()=>{const runtime=fixture(),webhookHandler={async handle(){return{accepted:true,status:202}}};await withServer({...runtime,apiKey:'x'.repeat(24),webhookHandler},async base=>{const response=await fetch(`${base}/webhooks/github`,{method:'POST',body:'{}'});assert.equal(response.status,202);assert.equal((await response.json()).accepted,true)})});
