import fs from 'node:fs/promises';
import { constants as fsConstants } from 'node:fs';
import path from 'node:path';
import { PlannerAgent, BuilderAgent, QaAgent } from './agents.js';
import { HashChainedAuditLog } from './audit-log.js';
import { attachBuilderRoutes } from './builder-router.js';
import { BrowserQaRunner, HttpBrowserQaExecutor } from './browser-qa-runner.js';
import { DeliveryGate } from './delivery.js';
import { DynamicPromptWorkspace } from './dynamic-workspace.js';
import { GitHubRestClient } from './github-client.js';
import { createModelProviderFromEnvironment } from './model-provider.js';
import { Orchestrator } from './orchestrator.js';
import { ProjectWorkspaceStore } from './project-workspace.js';
import { HttpJsonProvider } from './providers.js';
import { SlidingWindowRateLimiter } from './rate-limit.js';
import { createRepositoryHandlers, DEFAULT_TOOL_ALLOWLIST } from './repository-tools.js';
import { ControlledSandboxRunner, HttpSandboxExecutor } from './sandbox-runner.js';
import { ToolGateway } from './security.js';
import { createService } from './service.js';
import { SoftwareBuilder } from './software-builder.js';
import { createStateStoreFromEnvironment } from './state-store-factory.js';
import { GitHubWorkflowEventHandler } from './webhook.js';

function required(name){const v=String(process.env[name]||'').trim();if(!v)throw new Error(`${name} is required`);return v}
function csv(v){return String(v||'').split(',').map(x=>x.trim()).filter(Boolean)}
const apiKey=required('SERVICE_API_KEY');if(apiKey.length<24)throw new Error('SERVICE_API_KEY must be at least 24 characters');
const {store:stateStore,metadata:stateMetadata}=createStateStoreFromEnvironment(process.env);const stateDirectory=stateMetadata.directory;
const legacyProvider=process.env.AGENT_PROVIDER_URL?new HttpJsonProvider({endpoint:process.env.AGENT_PROVIDER_URL,apiKey:process.env.AGENT_PROVIDER_API_KEY||null,timeoutMs:Number(process.env.AGENT_PROVIDER_TIMEOUT_MS||30000),maxResponseBytes:Number(process.env.AGENT_PROVIDER_MAX_RESPONSE_BYTES||1024*1024),allowedHosts:csv(process.env.AGENT_PROVIDER_ALLOWED_HOSTS),allowHttp:String(process.env.AGENT_PROVIDER_ALLOW_HTTP||'').toLowerCase()==='true'}):null;
const provider=legacyProvider||createModelProviderFromEnvironment(process.env);
const targetRepository=String(process.env.TARGET_REPOSITORY||'').trim(),targetBranch=String(process.env.TARGET_BRANCH||'feature/agent-build').trim(),targetBase=String(process.env.TARGET_BASE||'main').trim(),githubToken=String(process.env.GITHUB_TOKEN||'').trim();let toolGateway=null,repositoryTarget=null,deliveryGate=null;
if(targetRepository||githubToken){if(!targetRepository||!githubToken)throw new Error('TARGET_REPOSITORY and GITHUB_TOKEN must be configured together');repositoryTarget={repository:targetRepository,branch:targetBranch,base:targetBase};const client=new GitHubRestClient({token:githubToken});const handlers=createRepositoryHandlers({client,allowedRepositories:[targetRepository],allowedBranches:[targetBranch],allowedBaseBranches:[targetBase]});toolGateway=new ToolGateway({allowlist:DEFAULT_TOOL_ALLOWLIST,handlers});deliveryGate=new DeliveryGate({toolGateway,repositoryTarget,prTitle:process.env.PR_TITLE||'Multi-agent build',prBody:process.env.PR_BODY||'Generated by multi-agent-build. Final merge requires explicit human approval.'});}
const planner=new PlannerAgent({provider}),builderAgent=new BuilderAgent({provider,toolGateway,repositoryTarget}),qa=new QaAgent({provider,toolGateway,repositoryTarget});
const orchestrator=new Orchestrator({planner,builder:builderAgent,qa,deliveryGate,stateStore,maxRepairAttempts:Number(process.env.MAX_REPAIR_ATTEMPTS||2)});
const workspace=provider?new DynamicPromptWorkspace({provider,stateStore}):null;
const sandboxUrl=String(process.env.SANDBOX_RUNNER_URL||'').trim(),sandboxToken=String(process.env.SANDBOX_RUNNER_TOKEN||''),sandboxTimeout=Number(process.env.SANDBOX_RUNNER_TIMEOUT_MS||240000),sandboxRunner=sandboxUrl?new ControlledSandboxRunner({executor:new HttpSandboxExecutor({endpoint:sandboxUrl,token:sandboxToken,timeoutMs:sandboxTimeout})}):null;
const browserQaUrl=String(process.env.BROWSER_QA_RUNNER_URL||sandboxUrl).trim(),browserQaRunner=browserQaUrl?new BrowserQaRunner({executor:new HttpBrowserQaExecutor({endpoint:browserQaUrl,token:String(process.env.BROWSER_QA_RUNNER_TOKEN||sandboxToken),timeoutMs:Number(process.env.BROWSER_QA_RUNNER_TIMEOUT_MS||240000)})}):null;
const projectDirectory=process.env.PROJECT_WORKSPACE_DIR||path.join(stateDirectory,'projects'),projectStore=new ProjectWorkspaceStore({directory:projectDirectory}),softwareBuilder=provider?new SoftwareBuilder({provider,projectStore,executionRunner:sandboxRunner,browserQaRunner,maxRepairAttempts:Number(process.env.MAX_REPAIR_ATTEMPTS||2),maxBrowserRepairAttempts:Number(process.env.MAX_BROWSER_REPAIR_ATTEMPTS||1)}):null;
const webhookSecret=String(process.env.GITHUB_WEBHOOK_SECRET||'').trim(),webhookHandler=webhookSecret?new GitHubWorkflowEventHandler({orchestrator,stateStore,webhookSecret}):null;
const auditDirectory=process.env.AUDIT_LOG_DIR||path.join(stateDirectory,'audit'),auditLog=new HashChainedAuditLog({directory:auditDirectory});const rateLimiter=new SlidingWindowRateLimiter({limit:Number(process.env.RATE_LIMIT_REQUESTS||60),windowMs:Number(process.env.RATE_LIMIT_WINDOW_MS||60000),maxKeys:Number(process.env.RATE_LIMIT_MAX_CLIENTS||10000)});
const groqConfigured=Boolean(process.env.GROQ_API_KEY||process.env.GROQ_KEY),nvidiaConfigured=Boolean(process.env.NVIDIA_NIM_API_KEY||process.env.NVIDIA_API_KEY||process.env.NIM_API_KEY),alibabaConfigured=Boolean(process.env.ALIBABA_API_KEY||process.env.DASHSCOPE_API_KEY),geminiConfigured=Boolean(process.env.GEMINI_API_KEY||process.env.GOOGLE_API_KEY);
const providerOptions=legacyProvider?['auto']:[ 'auto', ...(groqConfigured?['groq']:[]), ...(nvidiaConfigured?['nvidia-nim']:[]), ...(alibabaConfigured?['alibaba']:[]), ...(geminiConfigured?['gemini']:[]) ];
const server=createService({orchestrator,stateStore,webhookHandler,workspace,apiKey,auditLog,rateLimiter,providerOptions,maxBodyBytes:Number(process.env.MAX_REQUEST_BYTES||1024*1024),readinessCheck:async()=>{await fs.mkdir(stateDirectory,{recursive:true,mode:0o700});await fs.mkdir(projectDirectory,{recursive:true,mode:0o700});await fs.access(stateDirectory,fsConstants.R_OK|fsConstants.W_OK);const probe=`${stateDirectory}/.readiness-probe-${process.pid}`;await fs.writeFile(probe,'ok\n',{mode:0o600});await fs.unlink(probe);return{ok:true,state_backend:stateMetadata.backend,durable_state_required:stateMetadata.durability_required,durable_state_mount:stateMetadata.durable_mount,provider_configured:Boolean(provider),prompt_workspace_enabled:Boolean(workspace),builder_enabled:Boolean(softwareBuilder),sandbox_execution_configured:Boolean(sandboxRunner),browser_qa_configured:Boolean(browserQaRunner),workspace_version:workspace?'v3.5-browser-qa-repair':null,research_mode_available:groqConfigured,provider_options:providerOptions,groq_configured:groqConfigured,nvidia_nim_configured:nvidiaConfigured,alibaba_configured:alibabaConfigured,gemini_configured:geminiConfigured,repository_automation_configured:Boolean(repositoryTarget),webhook_configured:Boolean(webhookHandler),rate_limit_requests:Number(process.env.RATE_LIMIT_REQUESTS||60)}}});
attachBuilderRoutes(server,{builder:softwareBuilder,providerOptions,maxBodyBytes:Number(process.env.MAX_REQUEST_BYTES||1024*1024),auditLog});
const port=Number(process.env.PORT||3000);server.listen(port,'0.0.0.0',()=>process.stdout.write(`multi-agent-build service listening on ${port}\n`));
