import fs from 'node:fs/promises';
import { constants as fsConstants } from 'node:fs';
import path from 'node:path';
import { PlannerAgent, BuilderAgent, QaAgent } from './agents.js';
import { HashChainedAuditLog } from './audit-log.js';
import { DeliveryGate } from './delivery.js';
import { GitHubRestClient } from './github-client.js';
import { createModelProviderFromEnvironment } from './model-provider.js';
import { Orchestrator } from './orchestrator.js';
import { HttpJsonProvider } from './providers.js';
import { SlidingWindowRateLimiter } from './rate-limit.js';
import { createRepositoryHandlers, DEFAULT_TOOL_ALLOWLIST } from './repository-tools.js';
import { ToolGateway } from './security.js';
import { createService } from './service.js';
import { createStateStoreFromEnvironment } from './state-store-factory.js';
import { GitHubWorkflowEventHandler } from './webhook.js';
import { PromptWorkspace } from './workspace.js';

function required(name){const v=String(process.env[name]||'').trim();if(!v)throw new Error(`${name} is required`);return v}
function csv(v){return String(v||'').split(',').map(x=>x.trim()).filter(Boolean)}

const apiKey=required('SERVICE_API_KEY');
if(apiKey.length<24)throw new Error('SERVICE_API_KEY must be at least 24 characters');

const {store:stateStore,metadata:stateMetadata}=createStateStoreFromEnvironment(process.env);
const stateDirectory=stateMetadata.directory;

const legacyProvider=process.env.AGENT_PROVIDER_URL?new HttpJsonProvider({
  endpoint:process.env.AGENT_PROVIDER_URL,
  apiKey:process.env.AGENT_PROVIDER_API_KEY||null,
  timeoutMs:Number(process.env.AGENT_PROVIDER_TIMEOUT_MS||30000),
  maxResponseBytes:Number(process.env.AGENT_PROVIDER_MAX_RESPONSE_BYTES||1024*1024),
  allowedHosts:csv(process.env.AGENT_PROVIDER_ALLOWED_HOSTS),
  allowHttp:String(process.env.AGENT_PROVIDER_ALLOW_HTTP||'').toLowerCase()==='true'
}):null;
const provider=legacyProvider||createModelProviderFromEnvironment(process.env);

const targetRepository=String(process.env.TARGET_REPOSITORY||'').trim();
const targetBranch=String(process.env.TARGET_BRANCH||'feature/agent-build').trim();
const targetBase=String(process.env.TARGET_BASE||'main').trim();
const githubToken=String(process.env.GITHUB_TOKEN||'').trim();
let toolGateway=null,repositoryTarget=null,deliveryGate=null;
if(targetRepository||githubToken){
  if(!targetRepository||!githubToken)throw new Error('TARGET_REPOSITORY and GITHUB_TOKEN must be configured together');
  repositoryTarget={repository:targetRepository,branch:targetBranch,base:targetBase};
  const client=new GitHubRestClient({token:githubToken});
  const handlers=createRepositoryHandlers({client,allowedRepositories:[targetRepository],allowedBranches:[targetBranch],allowedBaseBranches:[targetBase]});
  toolGateway=new ToolGateway({allowlist:DEFAULT_TOOL_ALLOWLIST,handlers});
  deliveryGate=new DeliveryGate({toolGateway,repositoryTarget,prTitle:process.env.PR_TITLE||'Multi-agent build',prBody:process.env.PR_BODY||'Generated by multi-agent-build. Final merge requires explicit human approval.'});
}

const planner=new PlannerAgent({provider});
const builder=new BuilderAgent({provider,toolGateway,repositoryTarget});
const qa=new QaAgent({provider,toolGateway,repositoryTarget});
const orchestrator=new Orchestrator({planner,builder,qa,deliveryGate,stateStore,maxRepairAttempts:Number(process.env.MAX_REPAIR_ATTEMPTS||2)});
const workspace=provider?new PromptWorkspace({planner:new PlannerAgent({provider}),builder:new BuilderAgent({provider}),qa:new QaAgent({provider}),stateStore,maxRepairAttempts:Number(process.env.MAX_REPAIR_ATTEMPTS||2)}):null;

const webhookSecret=String(process.env.GITHUB_WEBHOOK_SECRET||'').trim();
const webhookHandler=webhookSecret?new GitHubWorkflowEventHandler({orchestrator,stateStore,webhookSecret}):null;
const auditDirectory=process.env.AUDIT_LOG_DIR||path.join(stateDirectory,'audit');
const auditLog=new HashChainedAuditLog({directory:auditDirectory});
const rateLimiter=new SlidingWindowRateLimiter({limit:Number(process.env.RATE_LIMIT_REQUESTS||60),windowMs:Number(process.env.RATE_LIMIT_WINDOW_MS||60000),maxKeys:Number(process.env.RATE_LIMIT_MAX_CLIENTS||10000)});

const server=createService({orchestrator,stateStore,webhookHandler,workspace,apiKey,auditLog,rateLimiter,maxBodyBytes:Number(process.env.MAX_REQUEST_BYTES||1024*1024),readinessCheck:async()=>{
  await fs.mkdir(stateDirectory,{recursive:true,mode:0o700});
  await fs.access(stateDirectory,fsConstants.R_OK|fsConstants.W_OK);
  const probe=`${stateDirectory}/.readiness-probe-${process.pid}`;
  await fs.writeFile(probe,'ok\n',{mode:0o600});
  await fs.unlink(probe);
  return {
    ok:true,
    state_backend:stateMetadata.backend,
    durable_state_required:stateMetadata.durability_required,
    durable_state_mount:stateMetadata.durable_mount,
    provider_configured:Boolean(provider),
    prompt_workspace_enabled:Boolean(workspace),
    groq_configured:Boolean(process.env.GROQ_API_KEY||process.env.GROQ_KEY),
    nvidia_nim_configured:Boolean(process.env.NVIDIA_NIM_API_KEY||process.env.NVIDIA_API_KEY||process.env.NIM_API_KEY),
    repository_automation_configured:Boolean(repositoryTarget),
    webhook_configured:Boolean(webhookHandler),
    rate_limit_requests:Number(process.env.RATE_LIMIT_REQUESTS||60)
  };
}});

const port=Number(process.env.PORT||3000);
server.listen(port,'0.0.0.0',()=>process.stdout.write(`multi-agent-build service listening on ${port}\n`));
