import fs from 'node:fs/promises';
import { PlannerAgent, BuilderAgent, QaAgent } from './agents.js';
import { DeliveryGate } from './delivery.js';
import { GitHubRestClient } from './github-client.js';
import { Orchestrator } from './orchestrator.js';
import { HttpJsonProvider } from './providers.js';
import { createRepositoryHandlers, DEFAULT_TOOL_ALLOWLIST } from './repository-tools.js';
import { ToolGateway } from './security.js';
import { createService } from './service.js';
import { JsonFileStateStore } from './state-store.js';
import { GitHubWorkflowEventHandler } from './webhook.js';

function required(name) {
  const value = String(process.env[name] || '').trim();
  if (!value) throw new Error(`${name} is required`);
  return value;
}

const apiKey = required('SERVICE_API_KEY');
if (apiKey.length < 24) throw new Error('SERVICE_API_KEY must be at least 24 characters');

const stateDirectory = process.env.WORKFLOW_STATE_DIR || '.multi-agent-runs';
const stateStore = new JsonFileStateStore({ directory: stateDirectory });
const provider = process.env.AGENT_PROVIDER_URL
  ? new HttpJsonProvider({
      endpoint: process.env.AGENT_PROVIDER_URL,
      apiKey: process.env.AGENT_PROVIDER_API_KEY || null,
      timeoutMs: Number(process.env.AGENT_PROVIDER_TIMEOUT_MS || 30000)
    })
  : null;

const targetRepository = String(process.env.TARGET_REPOSITORY || '').trim();
const targetBranch = String(process.env.TARGET_BRANCH || 'feature/agent-build').trim();
const targetBase = String(process.env.TARGET_BASE || 'main').trim();
const githubToken = String(process.env.GITHUB_TOKEN || '').trim();

let toolGateway = null;
let repositoryTarget = null;
let deliveryGate = null;

if (targetRepository || githubToken) {
  if (!targetRepository || !githubToken) throw new Error('TARGET_REPOSITORY and GITHUB_TOKEN must be configured together');
  repositoryTarget = { repository: targetRepository, branch: targetBranch, base: targetBase };
  const client = new GitHubRestClient({ token: githubToken });
  const handlers = createRepositoryHandlers({
    client,
    allowedRepositories: [targetRepository],
    allowedBranches: [targetBranch],
    allowedBaseBranches: [targetBase]
  });
  toolGateway = new ToolGateway({ allowlist: DEFAULT_TOOL_ALLOWLIST, handlers });
  deliveryGate = new DeliveryGate({
    toolGateway,
    repositoryTarget,
    prTitle: process.env.PR_TITLE || 'Multi-agent build',
    prBody: process.env.PR_BODY || 'Generated by multi-agent-build. Final merge requires explicit human approval.'
  });
}

const orchestrator = new Orchestrator({
  planner: new PlannerAgent({ provider }),
  builder: new BuilderAgent({ provider, toolGateway, repositoryTarget }),
  qa: new QaAgent({ provider, toolGateway, repositoryTarget }),
  deliveryGate,
  stateStore,
  maxRepairAttempts: Number(process.env.MAX_REPAIR_ATTEMPTS || 2)
});

const webhookSecret = String(process.env.GITHUB_WEBHOOK_SECRET || '').trim();
const webhookHandler = webhookSecret
  ? new GitHubWorkflowEventHandler({ orchestrator, stateStore, webhookSecret })
  : null;

const server = createService({
  orchestrator,
  stateStore,
  webhookHandler,
  apiKey,
  maxBodyBytes: Number(process.env.MAX_REQUEST_BYTES || 1024 * 1024),
  readinessCheck: async () => {
    await fs.mkdir(stateDirectory, { recursive: true, mode: 0o700 });
    await fs.access(stateDirectory, fs.constants?.R_OK | fs.constants?.W_OK).catch(async () => {
      await fs.access(stateDirectory);
    });
    return {
      ok: true,
      provider_configured: Boolean(provider),
      repository_automation_configured: Boolean(repositoryTarget),
      webhook_configured: Boolean(webhookHandler)
    };
  }
});

const port = Number(process.env.PORT || 3000);
server.listen(port, '0.0.0.0', () => {
  process.stdout.write(`multi-agent-build service listening on ${port}\n`);
});
